<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => 'http://womvts.womsolutions.in/gps/public/geturl?vg=SURESHLUX:WOM',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'GET',
  CURLOPT_HTTPHEADER => array(
    'Cookie: DO-LB="MTAuMTMwLjI0NS4xNzo4MA=="; XSRF-TOKEN=eyJpdiI6IjcxWnNWeHd2cFJHYWlFT3lkNjJJWGc9PSIsInZhbHVlIjoiN2hEa21KNWxTOG1nYUhQdnBROU9OWnBVVU1ZeVk2S2hCSkVRSTNWR1QwYWo3K1AwRUNpd1ZGRUFlVkFOQlZuYSIsIm1hYyI6ImZlODY0YmJhOTY5YTE0YTBmZTI1Y2YyYWYwMWJiNDdhM2YzYzUyMTQyMjMzNDk2NTlhNzAwNGIzYzIxNDZiZGQifQ%3D%3D; laravel_session=eyJpdiI6IlBLMzlKdkZYZ3ZiSHU2Ykt6MElDUHc9PSIsInZhbHVlIjoiY3ZUOXlKVXBQbWFETzR2Y2dMOUlOSEk3K2JcL0dlMHViU2RHdTFWSDJBU1VxN0J1WkVSbW1mdFdnYUdkMCtcL0h2IiwibWFjIjoiNzJhY2UxMDJlZDFmOWIzNzA5MTM4NThmYjQ1MTQyMzI5YjQ4YzQ3YTQyMDZlZDNlNzFjNjYyYzhlMzRlYjZjZiJ9'
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;
